# Travis CI (https://travis-ci.org/)
# This will only work on your repo if you have an account on travis and you
# have set it up to run continuous integration on this this repo

# Linux distribution (bionic beaver)
dist: focal

# Language and version
language: node_js
node_js:
  - "11"

branches:
  only:  # only run the CI for those branches 
  - master
  - dev

env:
  global: # Define environment variables for bash
    - OCTFLAGS="--no-gui --no-window-system --silent"

before_install:
  - travis_retry sudo apt-get -y -qq update
  # Install octave
  - travis_retry sudo apt-get -y install octave
  - travis_retry sudo apt-get -y install liboctave-dev
  # Install javascript node and node package manager necessary to run the validator
  - travis_retry sudo apt-get -y install nodejs
  - travis_retry sudo apt-get -y install npm
  # Install BIDS-Validator
  - sudo npm install -g bids-validator@1.5.7

install:
  # make octave file the JSONio submodule
  - cd lib/JSONio; mkoctfile --mex jsonread.c jsmn.c -DJSMN_PARENT_LINKS; cd ../..
  - octave $OCTFLAGS --eval "addpath (pwd); savepath ();"

before_script:
  # Add to src functions to path
  - octave $OCTFLAGS --eval "addpath(genpath(fullfile(pwd, 'src'))); savepath ();"
  # Change current directory
  - cd manualTests

jobs:
  include:

    - name: "BIDS validator: create and check dataset"
      script: octave $OCTFLAGS --eval "test_makeRawDataset" && bids-validator `pwd`/output/raw/ --ignoreNiftiHeaders
